-- Migrare: utilizatori cu id numeric auto-increment și profil ca coloane (nu JSON)
-- Rulează în Supabase SQL Editor (schema public)
--
-- Atenție: scriptul recreează tabelele de users/favorite/comenzi (pierde datele din ele).

BEGIN;

-- Necesare pentru gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1) Drop tabele dependente (chei străine către utilizatori / produse)
DROP TABLE IF EXISTS public.istoric_comenzi CASCADE;
DROP TABLE IF EXISTS public.comenzi_produse CASCADE;
DROP TABLE IF EXISTS public.comenzi CASCADE;
DROP TABLE IF EXISTS public.produse_favorite CASCADE;
DROP TABLE IF EXISTS public.utilizatori CASCADE;

-- 2) Utilizatori – id numeric (1,2,3...), profil ca coloane
CREATE TABLE public.utilizatori (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username         text NOT NULL UNIQUE,
  password         text NOT NULL,
  role             text NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin')),
  age_group        text NOT NULL,
  budget_range     text NOT NULL,
  interests        text[] NOT NULL DEFAULT '{}',
  preferred_brands text[] NOT NULL DEFAULT '{}',
  created_at       timestamptz DEFAULT now(),
  updated_at       timestamptz DEFAULT now()
);

-- 3) Produse – creează tabela dacă nu există (necesară pentru chei străine)
CREATE TABLE IF NOT EXISTS public.produse (
  id              text PRIMARY KEY,
  name            text NOT NULL,
  category        text NOT NULL,
  brand           text NOT NULL,
  price           numeric NOT NULL,
  description     text,
  image_url       text,
  specs           jsonb,
  stock           integer NOT NULL DEFAULT 0,
  supplier        text NOT NULL DEFAULT '',
  delivery_method text NOT NULL DEFAULT '',
  is_active       boolean NOT NULL DEFAULT true,
  tags            text[] DEFAULT '{}',
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

-- 4) Favorite
CREATE TABLE public.produse_favorite (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    integer NOT NULL REFERENCES public.utilizatori(id) ON DELETE CASCADE,
  product_id text NOT NULL REFERENCES public.produse(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE (user_id, product_id)
);

-- 5) Comenzi
CREATE TABLE public.comenzi (
  id                   text PRIMARY KEY,
  user_id              integer NOT NULL REFERENCES public.utilizatori(id) ON DELETE CASCADE,
  total_amount         numeric NOT NULL,
  status               text NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','confirmed','shipped','delivered','cancelled')),
  shipping_full_name   text,
  shipping_address     text,
  shipping_city        text,
  shipping_postal_code text,
  shipping_country     text NOT NULL DEFAULT 'Romania',
  shipping_phone       text,
  shipping_email       text,
  created_at           timestamptz DEFAULT now(),
  updated_at           timestamptz DEFAULT now()
);

-- 6) Comenzi produse
CREATE TABLE public.comenzi_produse (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id     text NOT NULL REFERENCES public.comenzi(id) ON DELETE CASCADE,
  product_id   text NOT NULL REFERENCES public.produse(id) ON DELETE RESTRICT,
  product_name text NOT NULL,
  quantity     integer NOT NULL,
  price        numeric NOT NULL,
  created_at   timestamptz DEFAULT now()
);

-- 7) Istoric comenzi
CREATE TABLE public.istoric_comenzi (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id     text NOT NULL REFERENCES public.comenzi(id) ON DELETE CASCADE,
  user_id      integer NOT NULL REFERENCES public.utilizatori(id) ON DELETE CASCADE,
  status       text NOT NULL,
  total_amount numeric NOT NULL,
  created_at   timestamptz DEFAULT now()
);

COMMIT;

